<?php
/**
 * Template Name: Google Drive Connector Product
 * Template Post Type: page, product
 *
 * @package Infometry_Custom_Templates
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
get_header();
$contact_url = home_url( '/contact-us/' );
$connectors_url = home_url( '/product/google-cloud-connectors/' );
$marketplace_url = 'https://marketplace.informatica.com/listings/cloud/connectors/infometry_google_drive_connector.html';
$guide_url = 'https://www.informatica.com/content/dam/informatica-marketplace/solutions/public/3357/Google%20Drive%20Connector%20User%20Guide.pdf';
$drive_icon = INFOMETRY_CT_URL . 'assets/images/google-connectors/google-drive.png';
$idmc_icon = INFOMETRY_CT_URL . 'assets/images/informatica-product-mark.png';
?>
<main class="igd-page" id="igd-main">
	<section class="igd-hero"><div class="igd-shell igd-hero-grid">
		<div class="igd-hero-copy"><h1>Google Drive Connector <em>for Informatica IDMC</em></h1><p>Automate secure file movement between Google Drive and enterprise systems with a native, no-code connector built for governed IDMC workflows.</p><div class="igd-actions"><a class="igd-button igd-primary" href="<?php echo esc_url( $contact_url ); ?>">Start a Free Trial <span>→</span></a><a class="igd-button igd-ghost" href="<?php echo esc_url( $marketplace_url ); ?>">View Marketplace <span>↗</span></a></div><div class="igd-hero-proof"><span><b>30-day</b> free trial</span><span><b>Unlimited</b> operations</span><span><b>24/7</b> support</span></div></div>
		<div class="igd-architecture" aria-label="Google Drive connects securely to Informatica IDMC"><div class="igd-arch-title"><span>Secure, native integration</span><b><i></i> Ready to connect</b></div><div class="igd-arch-flow"><div class="igd-app"><span><img src="<?php echo esc_url( $drive_icon ); ?>" alt="Google Drive"></span><small>Source or target</small><strong>Google Drive</strong></div><div class="igd-connector"><span>Native connector</span><div class="igd-pipeline" aria-hidden="true"><i></i></div><small>No-code</small></div><div class="igd-app"><span><img src="<?php echo esc_url( $idmc_icon ); ?>" alt="Informatica IDMC"></span><small>Map and automate</small><strong>Informatica IDMC</strong></div></div><div class="igd-arch-bottom"><span><i></i> OAuth 2.0</span><span><i></i> Secure Agent</span><span><i></i> No data stored</span></div></div>
	</div></section>
	<section class="igd-operations"><div class="igd-shell"><span>Supported operations</span><div><b>Upload</b><b>Download</b><b>Search</b><b>Create</b><b>Update</b><b>Delete</b><b>Permissions</b><b>Revisions</b></div></div></section>
	<section class="igd-outcomes"><div class="igd-shell"><div class="igd-heading"><span>Why teams choose it</span><h2>Replace manual file work with governed automation.</h2><p>A focused connector experience for moving, managing and operationalizing Drive content through IDMC.</p></div><div class="igd-outcome-grid"><article><i class="is-blue">01</i><h3>Automate movement</h3><p>Schedule uploads, downloads and bulk file transfers without scripts or repetitive handoffs.</p></article><article><i class="is-green">02</i><h3>Govern access</h3><p>Work with file permissions, metadata, Shared Drives and multiple Google connections securely.</p></article><article><i class="is-yellow">03</i><h3>Scale through IDMC</h3><p>Use Drive as a source or target across mappings, mapping tasks and synchronization tasks.</p></article></div></div></section>
	<section class="igd-capabilities" id="capabilities"><div class="igd-shell igd-cap-layout"><div class="igd-cap-intro"><span class="igd-label">Complete file lifecycle</span><h2>One connector.<br>Every essential Drive workflow.</h2><p>Designed for technical and business teams, with no custom coding required.</p><a href="<?php echo esc_url( $guide_url ); ?>">Download user guide <span>↗</span></a></div><div class="igd-cap-groups">
		<article><div class="igd-cap-icon is-blue">F</div><div><span>File management</span><h3>Move and manage content</h3><p>List files, fetch content, upload, download, create, update, delete and search.</p><ul><li>Google and non-Google formats</li><li>Multiple-file downloads</li><li>Source and target support</li></ul></div></article>
		<article><div class="igd-cap-icon is-green">A</div><div><span>Access & governance</span><h3>Control every connection</h3><p>Retrieve permissions and metadata across personal, shared and team environments.</p><ul><li>Shared with me files</li><li>Team and Shared Drives</li><li>OAuth refresh tokens</li></ul></div></article>
		<article><div class="igd-cap-icon is-red">C</div><div><span>Collaboration context</span><h3>Keep activity connected</h3><p>Bring comments, replies and revision details into downstream workflows.</p><ul><li>Comment and reply retrieval</li><li>Revision tracking</li><li>Agentic AI-ready metadata</li></ul></div></article>
	</div></div></section>
	<section class="igd-how"><div class="igd-shell"><div class="igd-heading igd-center"><span>How it works</span><h2>From trial to first workflow in three clear steps.</h2></div><div class="igd-step-grid"><article><b>01</b><div><h3>Activate</h3><p>Start a 30-day Marketplace trial and activate the connector for your OrgID.</p></div></article><article><b>02</b><div><h3>Connect</h3><p>Configure Google OAuth credentials, Drive scope and the IDMC Secure Agent.</p></div></article><article><b>03</b><div><h3>Automate</h3><p>Build a mapping or synchronization task and schedule your governed workflow.</p></div></article></div></div></section>
	<section class="igd-usecases"><div class="igd-shell igd-use-layout"><div><span class="igd-label">Enterprise use cases</span><h2>Built for the files your business depends on.</h2><p>Connect collaborative Drive content to the systems where teams analyze, govern and act on it.</p></div><div class="igd-use-grid"><article><span>01</span><h3>Scheduled reporting</h3><p>Move finance, sales and operations files into warehouses and analytics pipelines.</p></article><article><span>02</span><h3>Cloud file ingestion</h3><p>Automate ETL inputs and outputs across cloud and on-premise systems.</p></article><article><span>03</span><h3>Shared workspace control</h3><p>Manage files, permissions and revisions across teams and environments.</p></article><article><span>04</span><h3>Workflow collaboration</h3><p>Use comments and replies as governed context in business processes.</p></article></div></div></section>
	<section class="igd-assurance"><div class="igd-shell"><div class="igd-assurance-copy"><span class="igd-label">Enterprise ready</span><h2>Certified connectivity that stays inside your IDMC environment.</h2><p>The connector runs through Informatica Secure Agent and Google APIs. It does not retain your business data.</p></div><div class="igd-assurance-list"><span><i>✓</i><b>Informatica certified</b><small>Validated for the IDMC ecosystem</small></span><span><i>✓</i><b>Secure execution</b><small>Runs in your managed environment</small></span><span><i>✓</i><b>Predictable licensing</b><small>Annual OrgID-based subscription</small></span><span><i>✓</i><b>Global support</b><small>24/7 coverage across time zones</small></span></div></div></section>
	<section class="igd-faq"><div class="igd-shell igd-faq-layout"><div><span class="igd-label">Frequently asked</span><h2>Everything you need to evaluate the connector.</h2><p>Need help with implementation or licensing? Our connector team can guide you.</p><a class="igd-text-link" href="<?php echo esc_url( $contact_url ); ?>">Talk to an expert →</a></div><div class="igd-questions"><details open><summary>Is the connector certified by Informatica?<span>+</span></summary><p>Yes. It is Informatica certified and listed on Informatica Marketplace.</p></details><details><summary>Which IDMC tasks are supported?<span>+</span></summary><p>Use Drive as a source or target in mappings, mapping tasks and synchronization tasks.</p></details><details><summary>Does it support Shared Drives?<span>+</span></summary><p>Yes. It supports personal Drive, Shared with me, Team Drive and Shared Drive operations.</p></details><details><summary>How does licensing work?<span>+</span></summary><p>A 30-day trial is available. Annual Prod and Non-Prod licenses are charged per OrgID with unlimited usage.</p></details></div></div></section>
	<section class="igd-cta"><div class="igd-shell"><div><span>Start with a 30-day trial</span><h2>Make Google Drive part of your governed data flow.</h2><p>Replace manual file transfers with native IDMC automation.</p></div><div><a class="igd-button igd-light" href="<?php echo esc_url( $contact_url ); ?>">Start Your Free Trial <span>→</span></a><a href="<?php echo esc_url( $marketplace_url ); ?>">View Marketplace listing</a></div></div></section>
	<footer class="igd-footer"><div class="igd-shell"><span>© 2026 Infometry Inc.</span><a href="<?php echo esc_url( $connectors_url ); ?>">All Google connectors</a><a href="<?php echo esc_url( $contact_url ); ?>">Contact us</a></div></footer>
</main>
<?php get_footer(); ?>
